version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install soos-sca --trusted-host pypi.python.org
  build:
    commands:

        - # ARGS:
        - # run soos-sca with the -h flag for help
        - # ARGS REQUIRING CUSTOMIZATION:
        - SOOS_PROJECT_NAME="sca-codebuild"
        
        - # ARGS WHERE CUSTOMIZATION IS OPTIONAL:
        - SOOS_MODE="run_and_wait"
        - SOOS_ON_FAILURE="continue_on_failure" # What to do if the scan fails. Defaults to "fail_the_build".
        - SOOS_DIRS_TO_EXCLUDE="soos"
        - SOOS_FILES_TO_EXCLUDE=""
        - SOOS_ANALYSIS_RESULT_MAX_WAIT=300
        - SOOS_ANALYSIS_RESULT_POLLING_INTERVAL=10
        - # ARGS WHERE CUSTOMIZATION IS OPTIONAL, BUT UNLIKELY:
        - SOOS_API_BASE_URL="https://qa-api.soos.io/api/"
        - SOOS_LOGGING_VERBOSITY="INFO" # SET TO DEBUG TO ENABLE
        
        - # CI ENGINE SPECIFIC:
        - eval SOOS_CHECKOUT_DIR="$CODEBUILD_SRC_DIR"
        - SOOS_COMMIT_HASH="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
        - SOOS_BRANCH_NAME=""                            # ENTER BRANCH NAME HERE IF KNOWN
        - SOOS_BRANCH_URI="${CODEBUILD_SOURCE_REPO_URL}" # ENTER BRANCH URI HERE IF KNOWN
        - SOOS_BUILD_VERSION=""                          # ENTER BUILD VERSION HERE IF KNOWN
        - SOOS_BUILD_URI=""                              # ENTER BUILD URI HERE IF KNOWN
        - SOOS_OPERATING_ENVIRONMENT="" # ENTER OPERATING ENVIRONMENT HERE IF KNOWN (default will be provided)
        - SOOS_INTEGRATION_NAME="AWSCodeBuild"

        - # **************************** Modify Above Only ***************#
        - mkdir -p "${SOOS_CHECKOUT_DIR}/soos/workspace"
        - cd "${SOOS_CHECKOUT_DIR}"
        - soos-sca
          -m="${SOOS_MODE}" 
          -of="${SOOS_ON_FAILURE}" 
          -dte="${SOOS_DIRS_TO_EXCLUDE}" 
          -fte="${SOOS_FILES_TO_EXCLUDE}" 
          -wd="${SOOS_CHECKOUT_DIR}" 
          -armw=${SOOS_ANALYSIS_RESULT_MAX_WAIT} 
          -arpi=${SOOS_ANALYSIS_RESULT_POLLING_INTERVAL} 
          -buri="${SOOS_API_BASE_URL}" 
          -scp="${SOOS_CHECKOUT_DIR}" 
          -pn="${SOOS_PROJECT_NAME}" 
          -v="${SOOS_LOGGING_VERBOSITY}"
